### ISSUE TITLE
Properly resume training.

### ISSUE THREAD

**Issue by warmspringwinds** [martinkersner/train-CRF-RNN#11]
Hello.

Could you, please, give an example of how to resume training using your code?

Thank you.

**Comment by martinkersner** [comment]
Hi @warmspringwinds!

You can try to use [this script](https://github.com/martinkersner/train-CRF-RNN/blob/master/resume_training.py). However, you should be aware that you have to change *snapshot_prefix* in *solver.prototxt*, otherwise it will rewrite your old models.

Cheers,

Martin

**Comment by warmspringwinds** [comment]
@martinkersner 

Thank you so much :+1:

**Comment by martinkersner** [comment]
In a case you would like to continue training without regular testing your net, you can run this command from your *python-scripts* directory

```bash
../caffe-crfrnn/build/tools/caffe train --solver=$SOLVER --snapshot=$SOLVERSTATE
```

where $SOLVER is the same solver.prototxt as you used before you paused training and  $SOLVERSTATE is the last model state (file with .solverstate extension) that was snapshotted during training.
