### ISSUE TITLE
Trained using three classes but predictions is fully black

### ISSUE THREAD

**Issue by Shehz** [martinkersner/train-CRF-RNN#15]
Hi,

I followed the instructions in the readme and sucessfully started training the system. I selected one model from the training and gave correct paths in crfasrnn.py file, but prediction is fully black. I'm new to this and I want to train with my custom dataset. But even with Pascal Voc 2012, im not getting any segmentation result. Should I change any other parameters?

Regards,
Shez

**Comment by martinkersner** [comment]
Hi @Shehz 

How many iterations did you train? Training CRF-RNN is rather time-consuming and as any other deep learning approach it requires a lot of training samples. Can you provide more information about your dataset?

You should be also aware that current state of code here does not lead to good segmentation results, but it will hopefully soon, therefore, for now you could try to use different model described here https://github.com/martinkersner/train-DeepLab.

Martin

**Comment by Shehz** [comment]
Hi Martin,

Thank you for your quick reply. I trained for 5000 iterations and used all the training samples for three classes from Pascal Voc 2012. I just followed the instructions from your readme to generate lmdb data files. I believe that training is done through solve.py, however in that the base weights are being loaded by already pre-trained caffemodel. But, I want to create my own caffemodel, rather than loading from already pre-trained one because I want to include new classes. Also, I had a look into train-DeepLab, does c++ supports Matio. 

-Shehz

**Comment by martinkersner** [comment]
Even though you want to add new classes you can/have to use weights of some pre-trained layers, otherwise training would take too long and wouldn't converge since you don't employ enough training samples.

The only layers that you have to start training from scratch are those whose *output_num* differs from pre-trained model, therefore some convolutional and all deconvolutional layers.

Also, 5000 iterations aren't sufficient, however you shouldn't see predictions fully black.

**Comment by Shehz** [comment]
Thank you for your reply. There was some problem in my training model, now I'm getting output. Now, I want to train the system with my own training samples, which contains only two categories and these are not there in Pascal Voc 2012. In Phase-I, I have to train the system with CNN until it gets converged and after that I have to load the model to CRN-RNN and start training again until it gets converged. As, you have mentioned I have to change the num_outputs based on number of categories. Is there anything else, which I should be careful of while generating lmdb files and training of the system. I just want to be sure, so that I can start training. 

Thank you in advance.

**Comment by martinkersner** [comment]
Well, you should be careful with everything. But I suspect that current way of initializing deconvolutional layers taken from [Longjon](https://gist.github.com/shelhamer/80667189b218ad570e82) is not correct.

**Comment by Shehz** [comment]
ok, is there any other CNN network on which I can rely upon so that I can use it for Phase-I training

**Comment by martinkersner** [comment]
You can try this https://github.com/martinkersner/train-DeepLab. However, I am not sure if you can mix it as you want. You should better decide for one network and then use it for all training.

**Comment by Shehz** [comment]
ok. Thank you

**Comment by prakarshupmanyu** [comment]
@Shehz I am getting a completely black output as well. I know it has been more than an year but by any chance do you still remember what was the problem in your case?
