### ISSUE TITLE
ImportError: No module named lmdb

### ISSUE THREAD

**Issue by Engineering-Course** [martinkersner/train-CRF-RNN#16]
When I run this command:
python data2lmdb.py
a bug comes out like this:
ImportError: No module named lmdb

What's the problem, please?

**Comment by martinkersner** [comment]
You have to install lmbd for python. Check this https://groups.google.com/forum/#!topic/caffe-users/3GTvtqccD4k.

**Comment by Engineering-Course** [comment]
Oh
I just realized it. Thanks.
