### ISSUE TITLE
pascal class and paletts

### ISSUE THREAD

**Issue by weiliu620** [martinkersner/train-CRF-RNN#19]

**Comment by weiliu620** [comment]
Great work. May I ask in ``` convert_from_color_segmentation```, where did you find information that you used to define the class (mapping from rgb in segmentation label to class) and pallette? I couldn't find them in original pascal voc webpage. 

Thanks!

**Comment by martinkersner** [comment]
Hi!

You should download [development kit](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCdevkit_18-May-2011.tar) from original website and in *VOCcode* directory you can find a file *VOClabelcolormap.m* with a function generating palette. 

Cheers,

Martin

**Comment by weiliu620** [comment]
Great. Thanks for the help!
