### ISSUE TITLE
Crazy log file....

### ISSUE THREAD

**Issue by anguszxd** [martinkersner/train-CRF-RNN#21]
Hello, @martinkersner , it's me again! :D
I'm training PASCAL VOC12 three classes following your instruction. Although the code runs well, I get some problems.
1. The size of trained model is very small.  The size of `TVG_CRFRNN_COCO_VOC.caffemodel` is about 500Mb. I load this caffemodel as base weights and after some iters I get new models, `train_iter_10000.caffemodel` for example. But the size of this model is as small as 172 bytes. Is it right?
2. When training the models, some training information is written into a log file. However, as the code runs very fast, the log file grows very fast ! After several hours, the log file turns to be 50Gb.... I think there's something wrong...

**Comment by anguszxd** [comment]
Here are some log info:
**I0615 20:25:32.638391 26152 solver.cpp:258]     Train net output #375520: data = -75.4584
I0615 20:25:32.638420 26152 solver.cpp:258]     Train net output #375521: data = -80.4584
I0615 20:25:32.638450 26152 solver.cpp:258]     Train net output #375522: data = -62.4584
I0615 20:25:32.638480 26152 solver.cpp:258]     Train net output #375523: data = -59.4584
I0615 20:25:32.638509 26152 solver.cpp:258]     Train net output #375524: data = -67.4584
I0615 20:25:32.638540 26152 solver.cpp:258]     Train net output #375525: data = -79.4584
I0615 20:25:32.638571 26152 solver.cpp:258]     Train net output #375526: data = -96.4584
I0615 20:25:32.638602 26152 solver.cpp:258]     Train net output #375527: data = -100.458
I0615 20:25:32.638651 26152 solver.cpp:258]     Train net output #375528: data = -101.458
I0615 20:25:32.638685 26152 solver.cpp:258]     Train net output #375529: data = -90.4584
I0615 20:25:32.638716 26152 solver.cpp:258]     Train net output #375530: data = -104.458
I0615 20:25:32.638747 26152 solver.cpp:258]     Train net output #375531: data = -109.458
I0615 20:25:32.638777 26152 solver.cpp:258]     Train net output #375532: data = -99.4584
I0615 20:25:32.638808 26152 solver.cpp:258]     Train net output #375533: data = -99.4584
I0615 20:25:32.638839 26152 solver.cpp:258]     Train net output #375534: data = -99.4584
I0615 20:25:32.638869 26152 solver.cpp:258]     Train net output #375535: data = -101.458
I0615 20:25:32.638898 26152 solver.cpp:258]     Train net output #375536: data = -91.4584
I0615 20:25:32.638928 26152 solver.cpp:258]     Train net output #375537: data = -70.4584
I0615 20:25:32.638958 26152 solver.cpp:258]     Train net output #375538: data = -45.4584
I0615 20:25:32.638989 26152 solver.cpp:258]     Train net output #375539: data = -57.4584
I0615 20:25:32.639020 26152 solver.cpp:258]     Train net output #375540: data = -75.4584
I0615 20:25:32.639051 26152 solver.cpp:258]     Train net output #375541: data = -66.4584
I0615 20:25:32.639081 26152 solver.cpp:258]     Train net output #375542: data = -30.4584
I0615 20:25:32.639113 26152 solver.cpp:258]     Train net output #375543: data = -51.4584
I0615 20:25:32.639147 26152 solver.cpp:258]     Train net output #375544: data = -53.4584
I0615 20:25:32.639176 26152 solver.cpp:258]     Train net output #375545: data = -37.4584
I0615 20:25:32.639209 26152 solver.cpp:258]     Train net output #375546: data = -58.4584
I0615 20:25:32.639238 26152 solver.cpp:258]     Train net output #375547: data = -56.4584**

**Comment by anguszxd** [comment]
Found problem. The modified prototxt file still has some problems. I have fixed it, and it seems to be right now.

**Comment by Sam813** [comment]
@anguszxd 
I have the same issue, may I know which part of prototext need modification?

**Comment by kangmengmeng** [comment]
@anguszxd @Sam813   Hi，I have the same issue. Could you tell me How do you solve the problem？Thank you!
