### ISSUE TITLE
Error produced when started to train

### ISSUE THREAD

**Issue by daofeng2007** [martinkersner/train-CRF-RNN#24]
My gpu GTX 960 only has 2GB. When I trained this model, it gave me the following error:
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0804 17:09:36.119483  6990 solver.cpp:48] Initializing solver from parameters: 
test_iter: 261
test_interval: 1333
base_lr: 1e-13
display: 50
max_iter: 100000
lr_policy: "fixed"
momentum: 0.99
weight_decay: 0.0005
snapshot: 1000
snapshot_prefix: "models/train"
solver_mode: GPU
net: "TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt"
test_initialization: false
F0804 17:09:36.119524  6990 solver.cpp:438] Cannot write to snapshot prefix 'models/train'.  Make sure that the directory exists and is writeable.
*** Check failure stack trace: ***
Is this due to low memory of GPU?Can this model be trained using CPU.

**Comment by martinkersner** [comment]
Hi @daofeng2007,

As you can read from error message: "Cannot write to snapshot prefix 'models/train'. Make sure that the directory exists and is writeable.". Check if that path exists, if not, create it. Also, 2GB RAM is not enough to train this model. I believe that it can be trained using CPU, but I haven't tried it personally.

Cheers,

Martin

**Comment by ArunJ1** [comment]
can some experts through light on the above error??

**Comment by ArunJ1** [comment]
I am also facing the same error and even after i changed the particular directory permision using 'sudo chmod 777' i face the same issue
