### ISSUE TITLE
 Error parsing text-format caffe.NetParameter: 224:3: Unknown enumeration value of "MULTI_STAGE_MEANFIELD" for field "type".

### ISSUE THREAD

**Issue by ys404314023** [martinkersner/train-CRF-RNN#25]
when i use python solve.py 2>&1 | tee train.log ,
why 
I0822 20:24:39.926784  4537 solver.cpp:96] Creating training net from net file: TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 224:3: Unknown enumeration value of "MULTI_STAGE_MEANFIELD" for field "type".
F0822 20:24:39.927047  4537 upgrade_proto.cpp:932] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt
*** Check failure stack trace: ***
thank you.

**Comment by martinkersner** [comment]
Hi @ys404314023,

You should use Caffe version linked in this repository. This question has already been asked many times, so check closed issues if you need detailed information.

Cheers,

Martin
