### ISSUE TITLE
Doubt on labelling of non-classes

### ISSUE THREAD

**Issue by srika91** [martinkersner/train-CRF-RNN#4]
Suppose I have only two classes background and people.If an image contains people and some other class(other than background),can other class locations be taken as background?If that is not happening can I make other classes value in key:value pair as zero in palette? bcz by doing so am just training for only two classes people and background and other classes are taken as background?I cannot see where is this happening in the current set of codes,kindly guide me here.

**Comment by srika91** [comment]
I think I have not put the question properly.In short,what happens to an image that contains classes we are interested in and the classes we are not interested. eg if interested class is "people",what happens to the image that contains not only"people" but also another not interested class "car"

**Comment by martinkersner** [comment]
I am not sure if I understand you correctly. If you train with class A, B and C, but the testing data contain even class C (which we didn't consider during training), the class C is going to be labeled as background.  Labels in which are not interested in are relabeled as background during preprocessing.

**Comment by srika91** [comment]
Does that preprocessing applies to training data,because even in images of A,B and C there may be class D?so what is happening to those pixels belonging to class D that may be present in images(.txt) of A,B and C?

**Comment by martinkersner** [comment]
As I said in previous comment "Labels in which are not interested in are relabeled as background during preprocessing."

**Comment by srika91** [comment]
OK thats great.Thank you for your patient reply
