### ISSUE TITLE
Labels from colors

### ISSUE THREAD

**Issue by AlexTS1980** [martinkersner/train-CRF-RNN#44]
For the convert_from_color_segmentation method, instead of looping through the array, did you try using np.logical_and for 3 dimensions? It should be faster and more pythonic.

**Comment by martinkersner** [comment]
@AlexTS1980 Thanks for pointing it out! It was actually fixed in different repo, but I forgot to update it in this one. https://github.com/martinkersner/train-CRF-RNN/commit/86f2508dca68e73b23ffd640223f339abcb9c3fd
