### ISSUE TITLE
What kind of license does this project have?

### ISSUE THREAD

**Issue by pdvelez** [martinkersner/train-CRF-RNN#46]

**Comment by martinkersner** [comment]
Hi @pdvelez!

For now there is no specified licence. If necessary, maybe I could include licence as is in crfasrnn repository https://github.com/torrvision/crfasrnn/blob/master/LICENSE.

Cheers,
Martin

**Comment by pdvelez** [comment]
Hi Martin,

Thanks! that would be great!

**Comment by martinkersner** [comment]
https://github.com/martinkersner/train-CRF-RNN/blob/master/LICENSE
