### ISSUE TITLE
Run crfasrnn_demo.py  with a snapshot 

### ISSUE THREAD

**Issue by charterscruz** [martinkersner/train-CRF-RNN#5]
Hello,

I have obtained a few snapshots following @martinkersner's precious readme.
Now I would like to test these snapshots using crfasrnn_demo.py and some sample images. But I guess that some changes have to be done to the prototxt file that was used during training, right? Could you kindly give some hints on this?

Best regards

**Comment by martinkersner** [comment]
Hi @charterscruz!

I added [script](https://github.com/martinkersner/train-CRF-RNN/blob/master/crfasrnn.py) and [prototxt](https://github.com/martinkersner/train-CRF-RNN/blob/master/TVG_CRFRNN_COCO_VOC_TEST_3_CLASSES.prototxt) file. Try them out!

Martin

**Comment by charterscruz** [comment]
Hello  @martinkersner ,

Thank you for your prompt answer.
When I try to run your script I get the following error:  
**Check failed: target_blobs[j]->num() == source_layer.blobs(j).num() (4 vs. 2)**

This happens not only with the script that you provided but also with crfasrnn_demo.py from crfasrnn repo.

Interestingly,  if I run exactly the TEST.prototxt you provided with the [TVG_CRFRNN_COCO_VOC.caffemodel](http://goo.gl/j7PrPZ), instead of the snapshots that I obtained with your training procedure, the script runs successfully (even though the output is all background). 
Is this a hint that I may have done something wrong during the training procedure?

Thank you once again.
Gonçalo

**Comment by martinkersner** [comment]
The error probably happens because you have different number of classes (1 + background) than I present (3 + background) in this repository. The lines in prototxt files that are necessary to change are commented.

**Comment by charterscruz** [comment]
Hi @martinkersner ,

Sorry for not answering this right away.
You were right. That was the error.

Thanks
