### ISSUE TITLE
Missing spatial.par

### ISSUE THREAD

**Issue by pierrebaque** [martinkersner/train-CRF-RNN#7]
Hello, 
Thanks for this code, it is very helpful, many people will use it.

I first downloaded and ran the prediction code from https://github.com/torrvision/crfasrnn. It works without fine at test time.

Then I downloaded your code and I followed exactly the procedure that you describe. I get the following error:

F0304 14:08:15.064934 136000 multi_stage_meanfield.cpp:66] Check failed: pFile The file 'spatial.par' is not found. Please create it with initial spatial kernel weights.

Do you know if there is something I am missing?

Thanks a lot

Pierre

**Comment by martinkersner** [comment]
Hi!

You probably have the similar problem as discussed [here](https://github.com/torrvision/crfasrnn/issues/19). Copy *spatial.par* and *bilateral.par* from *python-scripts/* to *caffe-crfrnn/src/caffe/layers/*. I hope it helps you to solve your problem.

Martin

**Comment by kkharinarayanan** [comment]
Hii
I faced the same issue. I could resolve it by putting both files in the root folder of train-CRF-RNN
Hari

**Comment by pierrebaque** [comment]
Hello,

Thanks I just did it and it resolves the issue.

Cheers
