### ISSUE TITLE
Error from protobuf " Reading dangerously large protocol message."

### ISSUE THREAD

**Issue by kkharinarayanan** [martinkersner/train-CRF-RNN#8]
Hii
I am trying to train the network exactly as you have given.  But once i call the solver , am getting this error.

[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 537962613
score2-ft is composed of zeros!
Exiting.

I looked at the issue in Caffe https://github.com/BVLC/caffe/issues/2721. But as far as i know he solved that by changing the stride, which is not valid here.

**Comment by pierrebaque** [comment]
I get the exact same error with "score2-ft is composed of zeros!"
It seems that all other layers are initialized fine though.

**Comment by martinkersner** [comment]
Hi @kkharinarayanan, @pierrebaque!

There is no problem with *Reading dangerously large protocol* message. I just forgot to commit [updated protoxt](https://github.com/martinkersner/train-CRF-RNN/commit/f402a9fa4d35d364c66c23e39ce69b7748642c79).

Martin

**Comment by kkharinarayanan** [comment]
Thanks.. @martinkersner 
It fixed that issue..

How ever, now I have an out of memory error... I think  2GB graphics card is not enough..

Hari

**Comment by martinkersner** [comment]
Yes, 2 GB of RAM are not enough.

**Comment by kkharinarayanan** [comment]
Hii @martinkersner 

Can you tell me what are you using to train the network ?

**Comment by martinkersner** [comment]
nVidia Tesla k40

**Comment by kkharinarayanan** [comment]
Thanks @martinkersner ..
I will try to get one titan X .
Will see if I can change image dimensions and try out with the current card too
Haru
